# Generated by Django 3.2 on 2021-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetsri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField(default='SOME STRING', max_length=1000)),
                ('image_url', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
    ]
